run_id: example_run
flow_cell_ID: FAZ58018
flow_cell_model: FLO-MIN114
dorado_model: dna_r10.4.1_e8.2_400bps_sup@v5.0.0        
kit: SQK-RBK114-24
dorado_bin: "~/utils/dorado-0.7.2-linux-x64/bin/dorado"
