cores: 1
executor: "slurm"
latency-wait: 60
jobs: 20

default-resources:
  mem_mb: 3000
  threads: 1
  runtime: 29m
  slurm_partition: "short"

set-resources:
  basecall:
    threads: 6
    mem_mb: 10000
    slurm_partition: "gpu"
    nodes: 1
    runtime: 1h