cluster: "sbatch --time={cluster.time} --mem={cluster.mem} --cpus-per-task={cluster.cpus} --qos={cluster.qos} {cluster.extra}"
jobs: 25
jobscript: "profiles/cluster/slurm_submit.sh"
cluster-config: "profiles/cluster/cluster_config.json"
cluster-cancel: scancel
jobname: "{rulename}_{jobid}"
latency-wait: 90

rerun-incomplete: True
printshellcmds: False
keep-going: False